# Generated by Django 5.2.6 on 2025-10-13 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, unique=True, verbose_name='адрес места')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='обновлен в')),
            ],
        ),
    ]
