# Generated by Django 5.2.6 on 2025-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Не обработан'), ('in_assembly', 'В сборке'), ('delivering', 'Передан в доставку'), ('delivered', 'Доставлен')], db_index=True, default='not_processed', max_length=20, verbose_name='статус заказа'),
        ),
    ]
