# Generated by Django 5.2.6 on 2025-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_called_at_alter_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'наличный'), ('cashless', 'безналичный')], db_index=True, default='cash', verbose_name='способ оплаты'),
        ),
    ]
