# Generated by Django 5.2.6 on 2025-10-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodcartapp.restaurantmenuitem', verbose_name='кто приготовит'),
        ),
    ]
