# Generated by Django 5.2.7 on 2025-10-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='restaurant',
        ),
    ]
